# Generated by Django 4.1.4 on 2022-12-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('sku', models.CharField(max_length=255, unique=True, verbose_name='sku')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('status', models.CharField(choices=[('in_stock', 'В наличии'), ('on_request', 'Под заказ'), ('expected', 'Ожидается поступление'), ('out_of_stock', 'Нет в наличии'), ('not_produce', 'Не производится')], default='in_stock', max_length=32)),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'sku', 'status'], name='apiapp_prod_name_9f91fb_idx'),
        ),
    ]
